[project]
name = "prompty"
version = "1.0.0.dev0"
description = "Prompty is a new asset class and format for LLM prompts that aims to provide observability, understandability, and portability for developers. It includes spec, tooling, and a runtime. This Prompty runtime supports Python"
authors = [
    {name = "Seth Juarez", email = "seth.juarez@microsoft.com"},
]
dependencies = [
    "pyyaml>=6.0.1",
    "pydantic>=2.8.2",
    "jinja2>=3.1.4",
    "openai>=1.35.10",
    "azure-identity>=1.17.1",
]
requires-python = ">=3.8"
readme = "README.md"
license = {text = "MIT"}

[build-system]
requires = ["pdm-backend"]
build-backend = "pdm.backend"


[tool.pdm]
distribution = true
