name: prompty Python build and publish

on:
  push:
    paths:
      - 'runtime/prompty/**'
    tags:
      - 'python/*'
  workflow_dispatch:

jobs:
  pypi-publish:
    name: upload release to PyPI
    runs-on: ubuntu-latest
    permissions:
      # This permission is needed for private repositories.
      contents: read
      # IMPORTANT: this permission is mandatory for trusted publishing
      id-token: write
    steps:
      - uses: actions/checkout@v3

      - uses: pdm-project/setup-pdm@v3

      - name: installd dependencies
        working-directory: ./runtime/prompty
        run: pdm install

      - name: write fake env file
        working-directory: ./runtime/prompty
        run: |
          echo "AZURE_OPENAI_ENDPOINT=https://fake\nAZURE_OPENAI_KEY=123432" > .env
          cat .env

      - name: test package
        working-directory: ./runtime/prompty
        run: pdm run pytest

      - name: build package
        working-directory: ./runtime/prompty
        run: pdm build

      - name: Publish package distributions to PyPI
        working-directory: ./runtime/prompty
        run: pdm publish --no-build